name: All-Platform Pull and Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest,busybox:stable-glibc'  # 设置默认的 Docker 镜像列表

jobs:
  inspect_platforms:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Inspect image manifest
        run: |
          images="${{ github.event.inputs.docker_images }}"
          IFS=',' read -r -a image_array <<< "$images"
          for image in "${image_array[@]}"; do
            > platforms.txt
            docker buildx imagetools inspect ${image} --raw | \
            jq -r '
              if .manifests then
                .manifests[].platform | 
                "\(.os)/\(.architecture)\(if .variant then "/"+.variant else "" end)"
              else
                "\(.os)/\(.architecture)\(if .variant then "/"+.variant else "" end)"
              end' | \
            sort | uniq > platforms.txt
            echo "镜像：${image}，支持平台如下：$(tr '\n' '，' < platforms.txt)"
            
            while IFS= read -r line; do
              docker pull "${image}" --platform "${line}"
              image_name="${image//\//_}"
              image_name="${image_name//:/_}"
              tag_name="${line//\//_}"
              docker save "${image}" -o "${image_name}-${tag_name}.tar"
              gzip -c "${image_name}-${tag_name}.tar" > "${image_name}-${tag_name}.tar.gz"
              rm "${image_name}-${tag_name}.tar"
              echo "下载打包成功： ${image_name}-${tag_name}.tar.gz"
            done < platforms.txt
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}/*.tar.gz
          retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天
